### ISSUE TITLE
this tool does not parse mdat 'hack' encoding with long ( 64bits ) length

### ISSUE THREAD

**Issue by plslvval** [frejoel/bmffparse#2] opened 2019-07-11 10:15 UTC
length of 1 is an invalid length that encode for the fact that real length is after the tag in 64bits big endian form.

i am testing a 3gpp file generated from an android tablet.

000c5d10: 0000 0000 0000 0000 0000 0000 0000 0000 ................
000c5d20: 0001 6d64 6174 0000 0000 000b 8ce9 2111 ..mdat........!.
000c5d30: 4500 1450 0146 fff1 0a5a 5a5a 5a5a 5a5a E..P.F...ZZZZZZZ

here length of mdat is not 1 but 0x00000000000b8ce9

(...)

------------------------------------
------------------------------------
| box: moov, size: 1731
------------------------------------
------------------------------------
| box: free, size: 808515
------------------------------------
------------------------------------
| box: mdat, size: 1
------------------------------------
| ##### Parser Not Found: dat

where i found some information about this :

http://fileformats.archiveteam.org/wiki/Boxes/atoms_format
and within https://www.cnwrecovery.com/html/3gp_recovery.html comment :

'the 4 byte length is set to 1 (otherwise an illegal value) and the 8 byte length then follows the tag name. This would be the case for the mdat tag. The other change is the tag 'stco' points to the absolute location of frame starts - this 4 byte length is now swapped with 'co64' which is a 64 bit (8 byte) pointer.'

**Comment by frejoel** [comment] 2019-07-12 01:54
Thanks for the feedback!

I will look into the 8 byte size, looking at the code it should be supported. I didn't see a test for it so it's probably a bug.

Can you clarify what the issue is with the 'stco' and 'co64' boxes? These should both be supported as specified in ISO/IEC 14496-12:2015, and I can't see anything obviously wrong with it.
I noticed I never added 'co64' to the example in bmffparse/examples/bmffinfo.c, is this what you're referring to?

Thanks again!

**Comment by plslvval** [comment] 2019-07-13 08:46
Hi,

Issue is with 'mdat' box, sorry for confusion the 'stco' and 'co64' comments are irrelevant for my problem, those came from the sentence i quoted.

To ease this , please find a download page to get the 1,6MB 3gp file that has this issue :

https://serveur.slv-valbonne.fr/fichierspartages/f.php?h=16FVobuB
( if displayed in french, use the 'Télécharger' button ).

I guess that generating code creates a 8 byte long to not have 4G limit if the fvideo stream should ever grow over this length, so it encoded in 8 byte even if actual length is lower.

**Comment by plslvval** [comment] 2019-07-13 10:46
I don't have ISO/IEC 14496-12:2015, but got a a ISO/IEC 14496-12 Fourth edition 2012-07-15.
In 4.2 object structure clause this is mentioned as largesize : size is 1 then the actual size is in the field largesize.
i don't see this supported in src/bmff.c size_t bmff_parse(..).

**Comment by frejoel** [comment] 2019-07-13 16:30
The fix is merged into master and it's working with the file you posted.

**Comment by plslvval** [comment] 2019-07-13 21:22
Wow you are quick ! and this works fine.

box: mdat, size: 756969

Thanks !

**Comment by frejoel** [comment] 2019-07-14 01:43
Cool, thanks.

**Closed by frejoel** 2019-07-14 01:43 UTC
